### ISSUE TITLE
Doesn't launch on M1 Pro 14 macOS 13.2

### ISSUE THREAD

**Issue by Padamdam** [mmmago/airslide#1]
Hi,

Thanks for building this app ! I was excited to try it but it doesn't launch.

When launching the app directly from Finder I get the little zoom in animation indicating that it was launched but nothing appears either on the dock or the menu bar (doesn't launch from anywhere : Launchpad, Raycast, Right click > Open).

I checked the console and found 3 identical errors : 

AirSlide (AppKit)
Subsystem : com.apple.runtime-issues
Category : Nib loading
Message : <private>

Let me know if you need anything for further troubleshooting.

Regards !

**Comment by mmmago** [comment]
Hello, can you try with the following attached .app ?  It should open the preference pane at launch, but I guess the issue is coming from somewhere else. Do you got these error in the XCode console when trying to build the app ?

[AirSlide.zip](https://github.com/mmmago/airslide/files/10551992/AirSlide.zip)

**Comment by Padamdam** [comment]
Hi,

Thanks for reaching back quickly !

Just tested, same behavior and same error in the console, however only 2 console errors instead of 3 but same info reported in the console.

Regards !

**Comment by mmmago** [comment]
I actually have the same problem on a VM, console output three consecutive "runningboardd" process errors saying : "RBSStateCapture remove item called for untracked item". 

Investigating !

**Comment by mmmago** [comment]
Found the culprit. @Padamdam could you try with latest v1.1.1 release ? Should fix the issue :)

**Comment by Padamdam** [comment]
Hi,

This release does indeed fix the launching issue. I'm greeted with the app's settings pane and the app works fine !

Thank you for fixing this so quickly.

Regards !
