### ISSUE TITLE
New Feature: trigger AirDrop after release dragging in Notch area

### ISSUE THREAD

**Issue by pilisir** [mmmago/airslide#2]
Nice job! I love this so much.
But I figure out it is easily to trigger by accident while using external display which arrange upon the MacBook and dragging files cross. 🥲 

In settings, add「 Trigger AirDrop after release dragging in Notch area 」 or 「 Trigger AirDrop after hover Notch area in X seconds」that cloud solve this problem maybe.

Thank you so much. 
Once again, nice job. 👍

**Comment by mmmago** [comment]
Real drag & drop in the notch is now set as default behaviour in 1.2.1 ! I myself ran into that issue, thanks for your submission :)

**Comment by pilisir** [comment]
Thank you so much 🤩
