### ISSUE TITLE
[Bug] Crash when click "Settings" on menu

### ISSUE THREAD

**Issue by pilisir** [mmmago/airslide#3]
Crash when click "Settings" on menu, both 1.2 and 1.2.1 

Terminal log
```
Last login: Fri Mar 31 21:34:09 on ttys001
/Applications/AirSlide.app/Contents/MacOS/AirSlide ; exit;
 user@MacBook-Pro-M2  ~  /Applications/AirSlide.app/Contents/MacOS/AirSlide ; exit;
[1]    2146 trace trap  /Applications/AirSlide.app/Contents/MacOS/AirSlide

Saving session...completed.
```

System Profiler
```
      System Version: macOS 13.3 (22E252)
      Kernel Version: Darwin 22.4.0
      Model Name: MacBook Pro
      Model Identifier: Mac14,9
      Chip: Apple M2 Pro
      Total Number of Cores: 12 (8 performance and 4 efficiency)
      Memory: 32 GB
      System Firmware Version: 8422.100.650
      OS Loader Version: 8422.100.650
```

Is it normal? 🤔

We appreciate your effort～

**Comment by mmmago** [comment]
Hey again, I can't reproduce the issue here. Does the app crash also when you try to click on your notch to open the pref. pane ?

**Comment by pilisir** [comment]
You are right!
Clicking under notch will shut AirSlide also 🧐

**Comment by mmmago** [comment]
Weird ! Will need more feedbacks on this issue to investigate.

**Comment by pilisir** [comment]
@mmmago , I found the report in Console app. 😃
Wish it helpful.

[AirSlide-2023-04-01-213549.ips.zip](https://github.com/mmmago/airslide/files/11129683/AirSlide-2023-04-01-213549.ips.zip)

**Comment by zhengxiechen** [comment]
Can also confirm that clicking settings will crash the app on my M1 Pro macbook.

**Comment by mmmago** [comment]
@pilisir @zhengxiechen Can you guys try the version in the following .zip and tell me if it works out for you ?

[AirSlide.zip](https://github.com/mmmago/airslide/files/11137600/AirSlide.zip)

**Comment by zhengxiechen** [comment]
> @pilisir @zhengxiechen Can you guys try the version in the following .zip and tell me if it works out for you ?
> 
> [AirSlide.zip](https://github.com/mmmago/airslide/files/11137600/AirSlide.zip)

I'm able to pop the settings with the new version. It is quite interesting that even if I quit the new version and open the v1.2 one, I was able to open the settings fine now. One thing I noticed now is that when I hover a file to the notch, the area does not glow on the edges anymore (not sure if it was a feature implemented previously), but I'm still able to pop the airdrop interface fine).

**Comment by mmmago** [comment]
> > @pilisir @zhengxiechen Can you guys try the version in the following .zip and tell me if it works out for you ?
> > [AirSlide.zip](https://github.com/mmmago/airslide/files/11137600/AirSlide.zip)
> 
> I'm able to pop the settings with the new version. It is quite interesting that even if I quit the new version and open the v1.2 one, I was able to open the settings fine now. One thing I noticed now is that when I hover a file to the notch, the area does not glow on the edges anymore (not sure if it was a feature implemented previously), but I'm still able to pop the airdrop interface fine).

It was because the userdefault data wasn't set with the older versions when opening the pref. pane. 
Uploading v 1.2.2 now with some other fixes that should works 👍🏼

**Comment by pilisir** [comment]
works now, thank you!
